export const GET_PAYMENT_GATEWAYS = "GET_PAYMENT_GATEWAYS";

export const SET_PAYMENT_USER_INFO = "SET_PAYMENT_USER_INFO";
export const SET_PAYMENT_INFO = "SET_PAYMENT_INFO";
export const STRIPE_PAYMENT_REQUEST = "STRIPE_PAYMENT_REQUEST"
export const SET_PAYMENT_ORDER_INFO = "SET_PAYMENT_ORDER_INFO"

