export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE"
export const ERROR_MESSAGE = "ERROR_MESSAGE"
export const WARNING_MESSAGE = "WARNING_MESSAGE"
export const CLEAR_ALL_MESSAGE = "CLEAR_ALL_MESSAGE"

export const LOADER = "LOADER"



