
export const SET_PAYMENT_CHECK_OUT_PAYMENT = "SET_PAYMENT_CHECK_OUT_PAYMENT";
export const SET_ORDER_DATA_CHECK_OUT_PAYMENT = "SET_ORDER_DATA_CHECK_OUT_PAYMENT"
export const CLEAR_CHECK_OUT_PAYMENT = "CLEAR_CHECK_OUT_PAYMENT";
