export const INITIAL_CONFIGURATION = "INITIAL_CONFIGURATION";
export const FETCH_ACTIVITY = 'FETCH_ACTIVITY';
export const NEW_ACTIVITY = 'NEW_ACTIVITY';



export const FETCH_STORE_ITEMS = 'FETCH_STORE_ITEMS'
